# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ankitube.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(700, 198)
        MainWindow.setMinimumSize(QtCore.QSize(700, 198))
        MainWindow.setMaximumSize(QtCore.QSize(700, 198))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 70, 161, 21))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.link_textbox = QtWidgets.QLineEdit(self.centralwidget)
        self.link_textbox.setGeometry(QtCore.QRect(90, 20, 421, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.link_textbox.setFont(font)
        self.link_textbox.setObjectName("link_textbox")
        self.start_time = QtWidgets.QSpinBox(self.centralwidget)
        self.start_time.setGeometry(QtCore.QRect(220, 70, 43, 24))
        self.start_time.setMaximum(599)
        self.start_time.setObjectName("start_time")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(180, 70, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(280, 70, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.end_time = QtWidgets.QSpinBox(self.centralwidget)
        self.end_time.setGeometry(QtCore.QRect(310, 70, 43, 24))
        self.end_time.setMinimum(1)
        self.end_time.setMaximum(600)
        self.end_time.setProperty("value", 10)
        self.end_time.setObjectName("end_time")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(370, 70, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox.setGeometry(QtCore.QRect(460, 70, 16, 21))
        self.checkBox.setText("")
        self.checkBox.setChecked(True)
        self.checkBox.setObjectName("checkBox")
        self.get_video_button = QtWidgets.QPushButton(self.centralwidget)
        self.get_video_button.setGeometry(QtCore.QRect(530, 20, 151, 71))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.get_video_button.setFont(font)
        self.get_video_button.setObjectName("get_video_button")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 20, 71, 31))
        self.label.setObjectName("label")
        self.progress_bar = QtWidgets.QProgressBar(self.centralwidget)
        self.progress_bar.setGeometry(QtCore.QRect(10, 110, 671, 31))
        self.progress_bar.setProperty("value", 0)
        self.progress_bar.setInvertedAppearance(False)
        self.progress_bar.setObjectName("progress_bar")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 700, 20))
        self.menubar.setObjectName("menubar")
        self.menu_file = QtWidgets.QMenu(self.menubar)
        self.menu_file.setObjectName("menu_file")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_help = QtWidgets.QAction(MainWindow)
        self.action_help.setObjectName("action_help")
        self.menu_file.addAction(self.action_help)
        self.menubar.addAction(self.menu_file.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.action_help.triggered.connect(lambda: self.showHelpDialog("Help")) 
        #^
        #have to use a lambda function if you want to pass a parameter within this framework
        #thank being said, I put a parameter in here for my own educational purposes, not because I needed to

        self.get_video_button.clicked(lambda: self.)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "Clip times (in seconds):"))
        self.label_3.setText(_translate("MainWindow", "Start:"))
        self.label_4.setText(_translate("MainWindow", "End:"))
        self.label_5.setText(_translate("MainWindow", "Keep audio?"))
        self.get_video_button.setText(_translate("MainWindow", "Get Video"))
        self.label.setText(_translate("MainWindow", "Enter Link:"))
        self.menu_file.setTitle(_translate("MainWindow", "File"))
        self.action_help.setText(_translate("MainWindow", "Info"))

    def showHelpDialog(self, tl):
        icon = QtWidgets.QMessageBox.Information

        #this is the easiest way to do a multi line string with easily understood formatting
        text =("Ankitube is designed to allow download of YouTube video clips easily for educational purposes. \n \n"
        "Simply copy the URL into the text box, enter the clip start and end times. "
        "FFMpeg is a required dependency to allow .mp4 to .webm conversion "
        "to ensure anki video player compatability.")
        
        title = tl
        msgBox = QtWidgets.QMessageBox(icon, title, text)
        msgBox.setStandardButtons(QtWidgets.QMessageBox.Cancel)

        msgBox.exec()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
